[package]
name = "struct-to-json-db-test"
version = "0.1.0"
edition = "2021"

[dependencies]
struct-to-json-db = {path="./struct-to-json-db"}
serde = {version = "1.0.203",features = ["derive"] }
serde_json = "1.0.117"
